FIRST_PATH = "./docs/languages.md"
SECOND_PATH = "./docs/en-US/README.md"
COMBINED_PATH = "README.md"

final = "[//]: <> (Do not edit this file. It's automatically generated by build_readme.py. Instead, edit the README in docs.\n\n"

print("Reading from:", FIRST_PATH)
with open(FIRST_PATH, "r", "utf-8") as f:
    final += f.read() + "\n"

print("Reading from:", SECOND_PATH)
with open(SECOND_PATH, "r", "utf-8") as f:
    final += f.read()

print("Writing to:", COMBINED_PATH)
with open(COMBINED_PATH, "w", "utf-8") as f:
    f.write(final)
